"""Pydantic request and response models, one module per area. These also drive the /docs page."""

from schemas.analysis import (  # noqa: F401
    AdditionalSkill,
    AnalysisResponse,
    AnalysisSummary,
    EducationEntry,
    Evidence,
    ExperienceEntry,
    MatchedSkill,
    MissingSkill,
    Priority,
    PriorityBreakdown,
    Profile,
    ProfileSkill,
    Score,
    Sources,
)
from schemas.app import HealthResponse, SampleDocument, SamplesResponse  # noqa: F401
from schemas.coaching import (  # noqa: F401
    AnswerRequest,
    FallbackReason,
    FeedbackPoint,
    FeedbackResponse,
    Grounding,
    InterviewQuestionOut,
    InterviewSetResponse,
    RoadmapItem,
    RoadmapResponse,
)
from schemas.evidence import (  # noqa: F401
    EvidenceSummary,
    FairnessFinding,
    FairnessResponse,
    GitHubClaim,
    GitHubLanguage,
    GitHubRequest,
    GitHubResponse,
    LinkedInRequest,
    LinkedInResponse,
    OnlyLinkedInSkill,
    RepoRef,
    RoleComparison,
    SkillComparison,
)
from schemas.jobs import (  # noqa: F401
    CandidateRow,
    CandidateUploadResponse,
    JobDetail,
    JobSkill,
    JobSummary,
    MatrixCell,
    UploadOutcome,
)
from schemas.resume_tools import (  # noqa: F401
    AtsResponse,
    BulletCheck,
    BulletIssue,
    CareerResponse,
    ContactFound,
    KeywordDiff,
    KeywordRow,
    KeywordSummary,
    ParsePreview,
    ParseStats,
    QualityResponse,
    QualitySummary,
    RewriteRequest,
    RewriteResponse,
    RewriteVariant,
    RoleFit,
    ScanCheck,
    SixSecondScan,
    Timeline,
    TimelineGap,
    TimelineItem,
)
