"""initial tables

Revision ID: 0001
Revises:
Create Date: 2026-09-26 06:10:48.295326
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resume_filename", sa.String(length=255), nullable=False),
        sa.Column("resume_text", sa.Text(), nullable=False),
        sa.Column("jd_source", sa.String(length=10), nullable=False),
        sa.Column("jd_filename", sa.String(length=255), nullable=True),
        sa.Column("jd_text", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("jd_source", sa.String(length=10), nullable=False),
        sa.Column("jd_filename", sa.String(length=255), nullable=True),
        sa.Column("jd_text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bullet_rewrites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bullet_rewrites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bullet_rewrites_analysis_id"), ["analysis_id"], unique=False)

    op.create_table(
        "external_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("external_checks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_external_checks_analysis_id"), ["analysis_id"], unique=False)

    op.create_table(
        "interview_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interview_sets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interview_sets_analysis_id"), ["analysis_id"], unique=False)

    op.create_table(
        "job_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_candidates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_candidates_analysis_id"), ["analysis_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_candidates_job_id"), ["job_id"], unique=False)

    op.create_table(
        "roadmaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roadmaps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roadmaps_analysis_id"), ["analysis_id"], unique=False)

    op.create_table(
        "interview_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["interview_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interview_questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interview_questions_set_id"), ["set_id"], unique=False)

    op.create_table(
        "interview_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("feedback", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["interview_questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interview_answers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interview_answers_question_id"), ["question_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interview_answers_question_id"))

    op.drop_table("interview_answers")
    with op.batch_alter_table("interview_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interview_questions_set_id"))

    op.drop_table("interview_questions")
    with op.batch_alter_table("roadmaps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roadmaps_analysis_id"))

    op.drop_table("roadmaps")
    with op.batch_alter_table("job_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_candidates_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_candidates_analysis_id"))

    op.drop_table("job_candidates")
    with op.batch_alter_table("interview_sets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interview_sets_analysis_id"))

    op.drop_table("interview_sets")
    with op.batch_alter_table("external_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_checks_analysis_id"))

    op.drop_table("external_checks")
    with op.batch_alter_table("bullet_rewrites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bullet_rewrites_analysis_id"))

    op.drop_table("bullet_rewrites")
    op.drop_table("jobs")
    op.drop_table("analyses")
    # ### end Alembic commands ###
